segments:
- telraam_segment_id: 155073
  street: Rozemarijnstraat
  direction_ab_label: Stadinwaarts
  direction_ba_label: Staduitwaarts
- telraam_segment_id: 9000006048
  street: Bernard Spaelaan
  direction_ab_label: Stadinwaarts
  direction_ba_label: Staduitwaarts
- telraam_segment_id: 155401
  street: Coupure Links
  direction_ab_label: Richting Groene Vallei
  direction_ba_label: Richting Verlorenkost
- telraam_segment_id: 9000008840
  street: Papagaaistraat
  direction_ab_label: Stadinwaarts
  direction_ba_label: Staduitwaarts
- telraam_segment_id: 9000006262
  street: Wispelbergstraat
  direction_ab_label: Richting Theresianenstraat
  direction_ba_label: Richting Papegaaistraat
- telraam_segment_id: 154163
  street: Annonciadenstraat
  direction_ab_label: Staduitwaarts
  direction_ba_label: Stadinwaarts
- telraam_segment_id: 9000011803
  street: Iepenstraat
  direction_ab_label: Richting Annonciadenstraat
  direction_ba_label: Richting Coupure Rechts
- telraam_segment_id: 9000007115
  street: Rooigemlaan
  direction_ab_label: Richting Bijloke
  direction_ba_label: Richting Brugse Vaart
